language: python

jobs:
  include:
    - name: "Python 3.7.5 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      before_install:
        - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
        - pip3 install -r requirements.txt
#    - name: "Python 3.7.5 on macOS"
#      os: osx
#      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
#      language: shell       # 'language: python' is an error on Travis CI macOS
#      before_install:
#        - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
#        - pip3 install -r requirements.txt --user
#    - name: "Python 3.6.7 on Windows"
#      os: windows           # Windows 10.0.17134 N/A Build 17134
#      language: shell       # 'language: python' is an error on Travis CI Windows
#      before_install:
#        - choco install python --version 3.6.7
#        - python -m pip install --upgrade pip
#        - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
#        - pip3 install -r requirements.txt
#      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH

install:
  - pip3 install .

# 'python' points to Python 2.7 on macOS but points to Python 3.8 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script:
  - coverage run -m unittest discover || python3 -m unittest discover || python -m unittest discover

after_success:
  - bash <(curl -s https://codecov.io/bash)
