language: python

cache:
  directories:
  - $HOME/.cache/pip

matrix:
  include:
    - env: PYTHON_VERSION="3.7" NUMPY_VERSION="*" SCIPY_VERSION="*" PANDAS_VERSION="*" PYTORCH_VERSION="*" SYMPY_VERSION="*"


install:
  - pip install coverage codecov
  - pip install -r requirements.txt .

script:
  - coverage run -m unittest discover

after_success:
  - codecov
